# Spring 配置
spring:
  datasource:
    # MySQL 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL 地址
    url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    # MySQL 用户
    username: root
    # MySQL 密码
    password: aimi1314.
    # MySQL 数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 20
      idle-timeout: 30000
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  web:
    resources:
      static-locations: classpath:/static/
# MyBatis 配置
mybatis:
  # mapper 的地址
  mapper-locations: classpath:mapper/*.xml
  # MyBatis 实体类的位置
  type-aliases-package: com.ricostone.communitymodule.Entity
  configuration:
    # MyBatis 采用主键自增
    use-generated-keys: true
    # MyBatis 采用驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com:
     ricostone:
      communitymodule:
       debug
# 端口号
server:
  port: 8080
  servlet:
    context-path: /community